apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests: 
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: kavishkamk/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: kavishkamk/comment
      context: comment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: kavishkamk/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: kavishkamk/moderation-service
      context: moderation-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: kavishkamk/post
      context: post
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: kavishkamk/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .